# This file was generated by GoReleaser. DO NOT EDIT.
cask "boilr" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/Ilyes512/boilr/releases/download/v#{version}/boilr_Darwin_x86_64.tar.gz"
      sha256 "cf3807a53100ed34aff9a8312a14a61edddd3acd1da281e791c92e8dd4652769"
    end
    on_arm do
      url "https://github.com/Ilyes512/boilr/releases/download/v#{version}/boilr_Darwin_arm64.tar.gz"
      sha256 "bddaf5283a58617a348eae608b2af35b42f30461e317238d4745875d13bb76fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ilyes512/boilr/releases/download/v#{version}/boilr_Linux_x86_64.tar.gz"
      sha256 "4bdf37d0b2d6a39b377f2f99233c389b373e6d12874cfc3192f97561053a497c"
    end
  end

  name "boilr"
  desc "Boilerplate template manager that generates files or directories from template repositories"
  homepage "https://github.com/Ilyes512/boilr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boilr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boilr"]
    end
  end

  # No zap stanza required

end
