# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boilr < Formula
  desc "Boilerplate template manager that generates files or directories from template repositories"
  homepage "https://github.com/Ilyes512/boilr"
  version "0.5.0-rc.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Ilyes512/boilr/releases/download/0.5.0-rc.1/boilr_Darwin_arm64.tar.gz"
      sha256 "472905f0af3a181b4eceaae7ffe21786dc9463454db7a70f12d0f53d501a0eb2"

      def install
        bin.install "boilr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ilyes512/boilr/releases/download/0.5.0-rc.1/boilr_Darwin_x86_64.tar.gz"
      sha256 "a34000813245bc6cc17b3e7dc8110cbba8f3c0a148f7dc1359a4d41e15708368"

      def install
        bin.install "boilr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Ilyes512/boilr/releases/download/0.5.0-rc.1/boilr_Linux_x86_64.tar.gz"
      sha256 "e108b3d9e29f496ed336f8130f6dd86248df6f4e1e941014a770eb640f7ec6d3"

      def install
        bin.install "boilr"
      end
    end
  end

  test do
    system "#{bin}/boilr --version"
  end
end
